### ISSUE TITLE
RFC #0001 - Multiline Comments

### ISSUE THREAD

**Issue by HTG-YT** [harcpylang/harcpy#1]
The Pull Request #1 for RFC 0001 has been merged. This RFC now enters the 14-day period of comments. Feel free to express your concerns/ideas/alternatives for the RFC.

See https://github.com/harcpylang/rfcs/issues/2

**Comment by Gary50613** [comment]
first comment

**Comment by HTG-YT** [comment]
Multiline comment support will land with the compiler rewrite. Closing.
